spring:
  datasource:
    #url: jdbc:mysql://192.168.137.169:3306/tester?serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/tester?serverTimezone=Asia/Shanghai
    username: root
    password: autotest0
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 6000
mybatis:
  #mybatis配置
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.tester.tester.Entity
  #配置mapper xml所以在的路径，这里是个数组
  configuration:
    cache-enabled: true
    #下划线驼峰互转
    map-underscore-to-camel-case: true
server:
  port: 8089
logging:
  file:
    log/info.log
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
